### PR TITLE
[Bug Fix] Fix Permission denied error in cuda_setup

### PR DESCRIPTION
**Pull request by KaiserWhoLearns**
Current path checking seems to introduce Permission Error when checking paths where the user do not have access to ([Issue 810](https://github.com/TimDettmers/bitsandbytes/issues/810) and [Issue 675](https://github.com/TimDettmers/bitsandbytes/issues/675)).

Combined the fix in [Pull Request644](https://github.com/TimDettmers/bitsandbytes/pull/644), along with another place that calls `(path / libname).is_file()` without checking user access.

Note: This problem will likely only happen when a user without root access tries to use the package, while the root user has some installations of CUDA.

### CODE REVIEW

**Comment by TomasAndersonFang** [comment]
Thanks, it solves my problem!!!

**Comment by manishiitg** [comment]
this solved my problem as well!!

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by TimDettmers** [comment]
I merged a different fix which changes the order of the permission try-catch. Would this solution have an additional advantage over the other?

**Comment by KaiserWhoLearns** [comment]
> I merged a different fix which changes the order of the permission try-catch. Would this solution have an additional advantage over the other?


Were you referring to the first try-catch that was changed? For the original order, the `PermissionError` will directly go into the `OSError` as it's a subclass of OSError, so the later `except` will never be reached.

**Comment by Titus-von-Koeller** [comment]
Ok, thanks for raising this issue and taking the initiative to solve it. Looking forward to merge your next contribution!

**Pull request closed without merging**
