### PR TITLE
Add `"lamb"` to `str2optimizer32bit`

### PR DESCRIPTION
**Pull request by EtienneDosSantos**
LAMB was missing in `str2optimizer32bit`.

### CODE REVIEW

**Comment by EtienneDosSantos** [comment]
> LGTM! I see the same issue exists for LARS too.

Had a look again at `bitsandbytes/optim` and it appears it's not just LARS but many other optimizer variants as well.

**Comment by skku-daniilkim** [comment]
Hello! Is there currently any workaround for this issue, while this is being reviewed.

**Comment by Titus-von-Koeller** [comment]
@EtienneDosSantos, really good catch and ready to merge. Thank you! There're still some peculiarities with this code base that have gone unnoticed and still a bunch of cleaning up to do.

It so helpful if attentive members from the community take a hand-on approach like you and help us improve things. Super grateful for that!

Always happy to get future contributions from you as well :) Don't hesitate to tag me personally if you need input on anything or something catches your attention that is high impact and shouldn't be overlooked.

**Comment by Titus-von-Koeller** [comment]
@skku-daniilkim I'll do a patch release in the next days, hopefully by early next week at latest.

For now you can see where BNB is installed and manually edit the files in the same way that you see in the diff of this PR. To find the install location you can do this:

```
In [1]: import inspect

In [2]: import bitsandbytes

In [3]: pkg_location = inspect.getfile(bitsandbytes)

In [4]: print(pkg_location)
/opt/conda/envs/bnb/lib/python3.8/site-packages/__init__.py
```

Then find the right file in the package directory structure of course.

**Pull request merged**
