### PR TITLE
Replace libcudart.so with PyTorch's CUDA APIs

### LINKED ISSUE #264: bug: OS call failed or operation not supported on NGC PyTorch
Hello bitsandbytes!

Trying to import `bitsandbytes` on a docker container(which has been spawned from [nvcr.io/nvidia/pytorch:22.05-py3](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags)), it fails with errors.

Here is a full log:
```sh
======================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/extras/CUPTI/lib64'), PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/cuda/lib'), PosixPath('/usr/local/cuda-11.6/include')}
warn(msg)
CUDA exception! Error code: OS call failed or operation not supported on this OS
CUDA exception! Error code: initialization error
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
warn(msg)
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
warn("The installed version of bitsandbytes was compiled without GPU support. "
```

The first CUDA exception(`OS call failed or operation not supported on this OS`) is raised from:
https://github.com/TimDettmers/bitsandbytes/blob/49a04253fb1f3e195cb0e9e79bdb01db7a490774/bitsandbytes/cuda_setup/main.py#L313
and the other one(`initialization error`) is raised from:
https://github.com/TimDettmers/bitsandbytes/blob/49a04253fb1f3e195cb0e9e79bdb01db7a490774/bitsandbytes/cuda_setup/main.py#L335

To reproduce, just run the commands below:
```sh
$ pip install --upgrade pip
$ pip install bitsandbytes
$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitsandbytes
```

### PR DESCRIPTION
**Pull request by rapsealk**
This PR resolves #264 
I opened this PR as #346 has been closed accidently.

### CODE REVIEW

**Comment by atkinson** [comment]
Pretty please, can this be merged and released?

**Comment by rapsealk** [comment]
@atkinson Glad to hear that it was helpful to you. I don't have sufficient authority to merge it by myself, so let's wait for @TimDettmers' feedback.

**Comment by Titus-von-Koeller** [comment]
@rapsealk Thanks for your input, this is very much appreciated! I looked into this, talked it through with Tim and will work on integrating this later this week. Basically, we will take your solution and combine it with some other tweaks that we have in mind to improve this module.

Will let you know once we have news.

**Comment by rapsealk** [comment]
@Titus-von-Koeller Thanks for the news! It would be a pleasure to help if needed.

**Comment by TimDettmers** [comment]
Thank you for the PR. This will resolve a couple of problems where the `libcuda.so` cannot be found. There are other issue the PR might create. Sometimes a user needs to use a different CUDA version for pytorch and bitsandbytes, but this is currently rare.

I am unsure how this fix behaves if another library version loads a different CUDA version before PyTorch loads its CUDA version. Since PyTorch is packaged with CUDA its not a problem for them, but it might create problems for bitsandbytes.

I will merge and try to write some test to check behavior with multiple CUDA versions installed. Otherwise, we can just hope it works for others with weird environments. 

Thanks again for your contribution!

**Pull request merged**
