### PR TITLE
Added scipy to requirements.txt

### PR DESCRIPTION
**Pull request by dulalbert**
Added scipy to requirements.txt as it is used but not added to requirements

### CODE REVIEW

**Comment by shadeMe** [comment]
+1

This breaks the conditional importing of `bitsandbytes`, i.e.,
```python
try:
    import bitsandbytes

    has_bitsandbytes = True
except ImportError:
    bitsandbytes = None  # type: ignore
    has_bitsandbytes = False
```
`has_bitsandbytes` will be `False` even if the user has the library installed (but not `scipy`) since the `ImportError` gets masked.

**Comment by danieldk** [comment]
I think that the dependency should also be added to the `install_requires`, otherwise `scipy` doesn't get installed when `pip install`-ing `bitsandbytes`.

**Comment by nazarov-yuriy** [comment]
@TimDettmers 
Could we merge it?
Apparently https://github.com/TimDettmers/bitsandbytes/commit/8a20cd864b3c890a51e27cb2f460382b75734b4a is not enough.

**Comment by rasbt** [comment]
Should be a quick merge in case this got forgotten 😅

**Comment by mnoukhov** [comment]
@TimDettmers is this ok to merge?

https://github.com/TimDettmers/bitsandbytes/commit/8a20cd864b3c890a51e27cb2f460382b75734b4a is indeed not enough. Anyone installing bitsandbytes through pip e.g. `pip install bitsandbytes` will not install `scipy` and code will error.
`scipy` needs to be added to the `install_requires`

**Comment by mnoukhov** [comment]
This still needs to be addressed. Easy fix, should be merged

**Comment by TimDettmers** [comment]
Sorry for the delay on this. Thanks for contributing this fix!

**Pull request merged**
