### PR TITLE
Solution to GPU not detected in Windows WSL

### PR DESCRIPTION
**Pull request by ksylvan**
This is the solution to https://github.com/TimDettmers/bitsandbytes/issues/336 and a few other issues about GPU not being
seen in Windows WSL.

TL;DR: The CUDA driver installed on Windows host is stubbed inside the WSL 2 as libcuda.so and we need to include
*that* directory location in `LD_LIBRARY_PATH`

### CODE REVIEW

**Comment by nivibilla** [comment]
This is actually written in the Nvidia documentation, however is missing in the wsl installation page.

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#mandatory-actions

**Comment by ksylvan** [comment]
Yes, @nivibilla - It's in the Linux sections - but not the windows WSL sections.

FYI, the WSL Ubuntu environment uses `/etc/ld.so.cache.d/` files for the majority of those librarues, so setting them in LD_LIBRARY_PATH is not strictly needed, but nothing mentions the need to include  `/usr/lib/wsl/lib` directory.

**Comment by nivibilla** [comment]
You're right, it should be mentioned in the docs for clarity. I didn't have issues with installing cuda this way and it worked for me. Just wanted to let you know.

**Comment by ksylvan** [comment]
Can we get this merged? It's simply an addition to `errors_and_solutions.md`. @TimDettmers

**Comment by TimDettmers** [comment]
Thank you, this is a great addition to the docs! Sorry for taking so long to respond here. Could you add this commit to the latest branch on main. I made a mess with a force push when pushing private code for the 4-bit beta.

**Pull request closed without merging**
