### PR TITLE
Cleanup involving a handful of failures, some optimization and a lot of code quality improvements

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull request overview
* Remove unused code (31f66895046efdb2c36f0ad7a98edb2c6d47ad61)
* Code quality improvements (1eec77d34c80b5e3b63b2e4bb4d57a7009258c8f, 0b078403ee2f9955a9eb9d612aeb617852930e6e, 7a3c9af05d92114034a1a61bc9827fb9f3122af0, b5cf7063410f6f97c27c8e6256a9184e41ff3eca, 7727fa4c8c6c1ef2b109120aff4196a0a6bf3ed6)
* Fix `Undefined variable` errors (f6978ae2a22652465a36b4ad85bb5f6b5ca97e77, 4a05df34c29545ff8d6997531cb12665cc549bb4)
* Fix dangerous oversights (697bd02c60abdfc6e77daa7a870e80e4dcb92cb9, ef70f2adcd9b833959c77a1488d12e07338c799e)
* Perform some very slight code optimizations (54bd6ed1d6e3a14ee7b14996308825726ec5d1c3, c6dad28a08ee4a9bc8848b649babed029455d644)

## Introduction
This PR acts as a follow-up of some of my previous work here, but now at a slightly larger scale. After #72 in particular, I realised that there may be some other situations of an oversight leading to an unexpected bug. As a result, I used some common tools to attempt to find some, and to improve the code quality at the same time. In particular, I used `isort`, `pyupgrade`, whitespace cleaning & new line fixing via `pre-commit`, and I used `pylint` and `flake8` to be notified of issues.

Note that this results in quite a lot of commits, each purposefully kept separate, allowing you to cherry-pick the commits if you feel like some of them are not to your liking. I'll elaborate on each individually as well, as the final diff is difficult to parse when looking at it all in one go, then you can verify each of them individually.

### Remove references to unused cli (31f66895046efdb2c36f0ad7a98edb2c6d47ad61)
`debug_cli` did not seem to be used. I suspect that this was a leftover of some experimenting, but I may be wrong.

### Remove trailing whitespace & ensure newline at EOF (1eec77d34c80b5e3b63b2e4bb4d57a7009258c8f)
Via `pre-commit`:
```yaml
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: fix-byte-order-marker
          - id: trailing-whitespace
          - id: end-of-file-fixer
```

### Simplify statements into equivalent, modern variants (0b078403ee2f9955a9eb9d612aeb617852930e6e)
Via `pyupgrade --py37-plus`. The changes e.g. are subclassing from `object`, calling `super()` with `super(ThisClass, self)`, or old-style syntax formatting. These changes should all work from Python 3.7 onwards (i.e. the lowest still supported Python version).

### Sort imports (7a3c9af05d92114034a1a61bc9827fb9f3122af0)
Via `isort`. Should result in equivalent code, unless there is some stuff that relies on importing in very specific orders, but I presume not.

### Fix critical bug in histogram_scatter_add_2d: Undefined variable (f6978ae2a22652465a36b4ad85bb5f6b5ca97e77)
`index2d` is not defined, but `index2` is. Presumably the latter was intended.

### Fix critical bug in PytorchLARS().step: Undefined variable (4a05df34c29545ff8d6997531cb12665cc549bb4)
`param` is not defined, but `p` is, which is a loop variable of `group["params"]`. Presumably `p` was intended.

### Removing unnecessary else's (b5cf7063410f6f97c27c8e6256a9184e41ff3eca)
Speaks for itself.

### Resolve dangerous default value [] as argument (697bd02c60abdfc6e77daa7a870e80e4dcb92cb9)
A list like this is a dangerous default value, as the default value is only initialised once, and reused for all calls of the function. Manipulations of the value are hence preserved between calls of the function. See https://pylint.pycqa.org/en/latest/user_guide/messages/warning/dangerous-default-value.html for more info.

### Fix bad indentation (ef70f2adcd9b833959c77a1488d12e07338c799e)
The indentation here was only 3 spaces, rather than 4 like everywhere else.

### Remove unused imports (54bd6ed1d6e3a14ee7b14996308825726ec5d1c3)
Speaks for itself, should not have any negative consequences.

### Remove f-prefix from strings that don't use formatting (7727fa4c8c6c1ef2b109120aff4196a0a6bf3ed6)
Some f-strings didn't use `{}` at all, meaning they could just as well be normal strings.

### Remove extraneous get_ptr calls (c6dad28a08ee4a9bc8848b649babed029455d644)
In these situations, `get_ptr` was called without the return value being used.

---

I've also removed [`to_be_fixed__complaints_by_linter.log`](https://github.com/TimDettmers/bitsandbytes/blob/main/to_be_fixed__complaints_by_linter.log) in this PR. That's not to say that all of these are fixed, but merely that the most crucial ones are. Also, these logs are quite outdated, I simply used fresh new ones instead. 

Let me know if you need anything from me at this point!

* Tom Aarsen

### CODE REVIEW

**Comment by TimDettmers** [comment]
Thank you for this extensive PR! This is awesome!

Having a short peek, all the changes look good, but I want to review it more carefully. I will have time to look at the details in the next few days.

**Comment by tomaarsen** [comment]
I've resolved the merge conflict. Hopefully this will help!

- Tom Aarsen

**Comment by tomaarsen** [comment]
Oooh, a new paper! Don't worry, I understand and respect that you must prioritize your paper. Don't worry about it taking a bit of time before you can tackle this PR.

**Review by TimDettmers — APPROVED** [review]
Thank you, Tom! Sorry for the further delay.

All of this is very straightforward and makes the code much cleaner. I should start using a linter :) 

Thanks again!

**Comment by tomaarsen** [comment]
No worries! Happy new year.

**Pull request merged**
