### PR TITLE
cleanup docs-build breaking install instructs

### PR DESCRIPTION
**Pull request by Titus-von-Koeller**
Hey @pnunna93, there was this stray docs file from 4 weeks ago that was breaking our docs build on any PR to the `multi-backend-refactor` branch. I'll have to remove it, but I think we should add a section on how to compile things correctly asap.

For now, I just cleaned up the docs that you added 4 weeks back (without including them in the TOC; that's why they [broke the build](https://github.com/TimDettmers/bitsandbytes/actions/runs/9398342316/job/25883476452?pr=1243#step:15:61)), but maybe we should combine that with some parts from [here](https://github.com/TimDettmers/bitsandbytes/discussions/1219#discussioncomment-9651643)?

@stevhliu What do you think about how to best place this and how to account for the matrix of possibilities between OS and different backends, e.g. Windows build from source is currently slightly different. All backends should also support Windows, unless it's an OS specific backend, like MPS.

On another note, I'm planning to include an easy installation path for the alpha release and then announce it on socials, to get he maximum of alpha/beta testers involved for early feedback.

I'm currently working on the following functionality to install the wheel directly from the Github artifact of our per-commit wheel build, e.g. `curl https://raw.githubusercontent.com/timdettmers/bitsandbytes/main/scripts/install-nightly-bnb.py | python -`. That way people don't have to deal with the hassle of compiling.

@pnunna93 We aren't yet building AMD specific wheels, right? Maybe you could task someone on your team with that?

Long-term, I would like to people to install with `pip install bitsandbytes[rocm]` but for now maybe we just bundle everything together in the default bnb wheel?

cc @younesbelkada cc @matthewdouglas

### CODE REVIEW

**Comment by Titus-von-Koeller** [comment]
@pnunna93 @stevhliu feel free to propose changes or do a PR to my PR. Would be great if we could move relatively quickly on this, as things are converging towards an official communication for the alpha release (hopefully tmr or early next week)

**Comment by Titus-von-Koeller** [comment]
> The torch version is for rocm6.0. Please reinstall 6.1 torch and build bitsandbytes again:
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.1/

We should include a pointer avoiding this pitfall as well.

**Comment by pnunna93** [comment]
I have opened a PR here to update ROCm installation steps - https://github.com/Titus-von-Koeller/bitsandbytes/pull/3

It includes changes mentioned in this thread.

**Comment by Titus-von-Koeller** [comment]
LGTM, thanks @pnunna93 and @stevhliu ❤️!

**Pull request merged**
