### PR TITLE
docs: fix broken links

### PR DESCRIPTION
**Pull request by Titus-von-Koeller**
The quant classes links on the index page currently give a 404.

### CODE REVIEW

**Comment by Titus-von-Koeller** [comment]
Ok, all links working again.

Quickly merging now to fix official docs.

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for fixing ! This should be good to merge no (I checked it on the rendered docs)?

**Comment by Titus-von-Koeller** [comment]
Yes, thanks for checking and getting things back on track in general 🤗 I also verified the docs, everything working, yay.

**Comment by younesbelkada** [comment]
Awesome work ! 🚀 thanks titus !

**Pull request merged**
